services:
  database:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: bookuser
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - database:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - database
    restart: unless-stopped
networks:
  database:
volumes:
  database: